# Generated by Django 5.1.7 on 2025-03-11 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='log',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='destination',
            name='http_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='received_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
